monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: debug
            handler: nested
#            excluded_404s:
#                # regex: exclude all 404 errors from the logs
#                - ^/
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            channels: ["!event", "!doctrine"]

        console:
            type:   console
            level:  debug
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]


#monolog:
#    handlers:
#        main:
#            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.log"
#            level: debug
#            channels: ["!event"]
#        # uncomment to get logging in your browser
#        # you may have to allow bigger header sizes in your Web server configuration
#        #firephp:
#        #    type: firephp
#        #    level: info
#        #chromephp:
#        #    type: chromephp
#        #    level: info
#        console:
#            type:   console
#            process_psr_3_messages: false
#            channels: ["!event", "!doctrine", "!console"]
